index:
   path: /
   controller: App\Controller\MainController::index

article:
   path: /article/{id}
   controller: App\Controller\ArticleController::index
   requirements:
      id: '\d+'

category:
   path: /category/{slug}
   controller: App\Controller\ArticleCategoryController::index
